wandb:
  project: "toxic-comments-classification"
  entity: "mlops-group-100"
model_artifact_path: "valhacks-syntax-terror-org/wandb-registry-ToxicTweets/models:latest"
model_name_or_path: "vinai/bertweet-base"