name: Unit Tests

on:
  push:
    branches:
      - main
      - fix-tests
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.12", "3.11"]
        pytorch-version: ["2.6.0", "2.7.0"]


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}


      - name: Install uv
        run: |
          python -m pip install -U pip
          pip install uv

      - name: Install dependencies
        run: |
          uv sync --all-groups
          uv pip install torch==${{ matrix.pytorch-version }}
          uv pip list

      - name: Auth with GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_CREDENTIALS }}

      - name: Pull data from DVC
        run: |
          uv run dvc pull --no-run-cache

      - name: Clear test cache
        run: |
          uv run pytest --cache-clear

      - name: Run tests with coverage
        run: |
          # Tell coverage where your source code is
          uv run coverage run --source=. -m pytest tests/
          
      - name: Generate coverage report
        run: |
          uv run coverage report -m --rcfile=pyproject.toml
          
      - name: Generate coverage XML (for badges)
        run: |
          uv run coverage xml
